# Generated by Django 5.1.4 on 2025-02-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_interviewavailability_interviewschedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interviewavailability",
            options={"verbose_name_plural": "interview availabilities"},
        ),
        migrations.AlterModelOptions(
            name="interviewschedule",
            options={"verbose_name_plural": "interview schedules"},
        ),
        migrations.AlterField(
            model_name="interviewavailability",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="interviewschedule",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
