# Generated by Django 5.1.4 on 2025-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_interviewavailability_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewavailability",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="interviewavailability",
            name="start_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="interviewschedule",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="interviewschedule",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
